### PR TITLE
Add node.js

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by jcftang** [comment]
Interesting, I thought nodejs required webkit for the java script engine.

**Comment by certik** [comment]
I thought nodejs requires the Google Javascript engine, which is included in the source code. I testing simple examples and those work.

**Comment by jcftang** [comment]
Ah ok, that makes more sense

**Comment by jcftang** [comment]
+1 for this, lets just merge it.

**Comment by certik** [comment]
Thanks.

**Pull request merged**
