### PR TITLE
Add hypre

### PR DESCRIPTION
**Pull request by johannesring**
This is inspired by the Homebrew receipt: [hypre.rb](https://github.com/Homebrew/homebrew-science/blob/master/hypre.rb)

### CODE REVIEW

**Comment by johannesring** [comment]
I'm not really sure how to best deal with the different BLAS/LAPACK implementations. Please let me know if there are any comments/suggestions.

**Comment by johannesring** [comment]
This is not tested on OS X yet. I will do that now, but I am not so sure it will work with PETSc since I do not have a Fortran compiler.

**Comment by johannesring** [comment]
Building a shared library for hypre did not work on OS X:

    2015/02/12 10:25:08 - INFO: [package:run_job] Making lib ...
    2015/02/12 10:25:08 - INFO: [package:run_job] Building libHYPRE.so ...
    2015/02/12 10:25:08 - INFO: [package:run_job] mpicc -shared -o libHYPRE-2.9.1a.so    /U\
    sers/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/IJ_mv/*.o /Users/johannr/.hashdist/tm\
    p/hypre-wytfdcc7aawl/src/distributed_ls/Euclid/*.o /Users/johannr/.hashdist/tmp/hypre-w\
    ytfdcc7aawl/src/distributed_ls/ParaSails/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc\
    7aawl/src/distributed_ls/pilut/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/\
    distributed_matrix/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/krylov/*.o /\
    Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/matrix_matrix/*.o /Users/johannr/.ha\
    shdist/tmp/hypre-wytfdcc7aawl/src/multivector/*.o /Users/johannr/.hashdist/tmp/hypre-wy\
    tfdcc7aawl/src/parcsr_ls/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/parcsr\
    _mv/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/parcsr_block_mv/*.o /Users/\
    johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/seq_mv/*.o /Users/johannr/.hashdist/tmp/hy\
    pre-wytfdcc7aawl/src/sstruct_ls/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src\
    /sstruct_mv/*.o /Users/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/struct_ls/*.o /User\
    s/johannr/.hashdist/tmp/hypre-wytfdcc7aawl/src/struct_mv/*.o /Users/johannr/.hashdist/t\
    mp/hypre-wytfdcc7aawl/src/utilities/*.o  -L/Users/johannr/.hashdist/bld/mpi/gkut75dahgi\
    l/lib   -L/Users/johannr/.hashdist/bld/lapack/xvzyk5hqp7ew/lib  -llapack -L/Users/johan\
    nr/.hashdist/bld/blas/orqin7luuh5d/lib  -lblas -lm  -Wl,-soname,libHYPRE-2.9.1a.so -Wl,\
    -z,defs
    2015/02/12 10:25:08 - INFO: [package:run_job] ld: warning: directory not found for opti\
    on '-L/Users/johannr/.hashdist/bld/lapack/xvzyk5hqp7ew/lib'
    2015/02/12 10:25:08 - INFO: [package:run_job] ld: warning: directory not found for opti\
    on '-L/Users/johannr/.hashdist/bld/blas/orqin7luuh5d/lib'
    2015/02/12 10:25:08 - INFO: [package:run_job] ld: unknown option: -soname
    2015/02/12 10:25:08 - INFO: [package:run_job] clang: error: linker command failed with \
    exit code 1 (use -v to see invocation)
    2015/02/12 10:25:08 - INFO: [package:run_job] make[1]: *** [libHYPRE.so] Error 1

Building without `--enable-shared' on OS X fixes this problem. This is the same as in [hypre.rb](https://github.com/Homebrew/homebrew-science/blob/master/hypre.rb).

**Comment by johannesring** [comment]
I'm having problems building the tests on OS X:

    [hypre] Building zboxloop ... 
    [hypre] mpicc -o zboxloop zboxloop.o -L/Users/johannr/.hashdist/tmp/hypre-qbfzwbzxl4zm-1/src/hypre/lib -lHYPRE -L/Users/johannr/.hashdist/bld/mpi/gkut75dahgil/lib     -L/usr/lib  -llapack -L/usr/lib  -lblas -L/Users/johannr/.hashdist/bld/blas/orqin7luuh5d/lib  -L/Users/johannr/.hashdist/bld/gnu-sed/65exdjxyi5e6/lib  -L/Users/johannr/.hashdist/bld/lapack/xvzyk5hqp7ew/lib  -L/Users/johannr/.hashdist/bld/mpi/gkut75dahgil/lib  -lm
    [hypre] ld: warning: directory not found for option '-L/Users/johannr/.hashdist/bld/blas/orqin7luuh5d/lib'
    [hypre] ld: warning: directory not found for option '-L/Users/johannr/.hashdist/bld/gnu-sed/65exdjxyi5e6/lib'
    [hypre] ld: warning: directory not found for option '-L/Users/johannr/.hashdist/bld/lapack/xvzyk5hqp7ew/lib'
    [hypre] Undefined symbols for architecture x86_64:
    [hypre]   "_hypre_BeginTiming", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_CAlloc", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]       _hypre_BoxArrayCreate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayArrayCreate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayDuplicate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayArrayDuplicate in libHYPRE.a(box.o)
    [hypre]   "_hypre_ClearTiming", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_EndTiming", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_FinalizeTiming", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_Free", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]       _hypre_BoxDestroy in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayDestroy in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayArrayDestroy in libHYPRE.a(box.o)
    [hypre]   "_hypre_InitializeTiming", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_MAlloc", referenced from:
    [hypre]       _hypre_BoxCreate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayCreate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayArrayCreate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxDuplicate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayDuplicate in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayArrayDuplicate in libHYPRE.a(box.o)
    [hypre]   "_hypre_MPI_Barrier", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_MPI_Comm_rank", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_MPI_Comm_size", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_MPI_Finalize", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_MPI_Init", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_PrintTiming", referenced from:
    [hypre]       _main in zboxloop.o
    [hypre]   "_hypre_ReAlloc", referenced from:
    [hypre]       _hypre_BoxArraySetSize in libHYPRE.a(box.o)
    [hypre]       _hypre_AppendBoxArray in libHYPRE.a(box.o)
    [hypre]       _hypre_AppendBox in libHYPRE.a(box.o)
    [hypre]   "_hypre__global_error", referenced from:
    [hypre]       _hypre_BoxSetExtents in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArraySetSize in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxDestroy in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayDestroy in libHYPRE.a(box.o)
    [hypre]       _hypre_BoxArrayArrayDestroy in libHYPRE.a(box.o)
    [hypre]       _hypre_AppendBoxArray in libHYPRE.a(box.o)
    [hypre]       _hypre_AppendBox in libHYPRE.a(box.o)
    [hypre]       ...
    [hypre] ld: symbol(s) not found for architecture x86_64
    [hypre] clang: error: linker command failed with exit code 1 (use -v to see invocation)
    [hypre] make[1]: *** [zboxloop] Error 1
    [hypre] make: *** [test] Error 2
    [hypre|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 2
    [hypre|ERROR] command failed (code=2); raising

Could it be because I do not have a Fortran compiler?

**Comment by johannesring** [comment]
When running with `without_check: true`, I get this when building `petsc`:

    [petsc] *******************************************************************************
    [petsc]          UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
    [petsc] -------------------------------------------------------------------------------
    [petsc] --with-hypre-lib=['/Users/johannr/.hashdist/bld/hypre/ke7tqjwfan7n/lib/libHYPRE.a'] and 
    [petsc] --with-hypre-include=['/Users/johannr/.hashdist/bld/hypre/ke7tqjwfan7n/include'] did not work
    [petsc] *******************************************************************************
    [petsc] 
    [petsc|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
    [petsc|ERROR] command failed (code=1); raising

The `configure.log` is avilable [here](https://gist.github.com/johannesring/4794db77e525571baa3b). This might also be because I do not have a Fortran compiler.

**Comment by ahmadia** [comment]
I generally use `homebrew` to install a GFortran compiler on OS X, since it's pretty reliable at providing a correct one.  I believe you install `homebrew` and then `gcc`.  As for how to get this to build correctly, I think the best trick is to figure out how PETSc installs hypre locally.  It may be worth pinging their mailing list if it's not obvious what they are doing.

**Comment by johannesring** [comment]
I was looking at `config/PETSc/packages/hypre.py` in the PETSc source code when creating this package. They require a Fortran compiler, so I was pretty sure that it wouldn't work without it.

I would like to avoid Homebrew for our FEniCS users, so hypre is not important for me on OS X for now.

**Comment by ahmadia** [comment]
Proteus has a few random Fortran dependencies, and I think this may be one of them.  I don't have time to look through this PR, but I might have time later.  Should we just put this on hold for when I've got some more time?

**Comment by johannesring** [comment]
Yes, that is fine with me.

**Comment by ahmadia** [comment]
I'm okay with merging this in.

**Comment by johannesring** [comment]
Thanks!

**Pull request merged**
