### PR TITLE
Refactor out-of-source build with CMake

### PR DESCRIPTION
**Pull request by chvillanuevap**
This Armadillo package:

```
build_stages:

  - name: configure
    build_in_source: true
```

produces the following build script:

```
set -e
export HDIST_IN_BUILD=yes
export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | sed -E "s/([0-9]+\.[0-9]+).*/\1/")

(
export CPPFLAGS="-I${CMAKE_DIR}/include"
export LDFLAGS="-L${CMAKE_DIR}/lib "
${CMAKE} -DCMAKE_INSTALL_PREFIX:PATH="${ARTIFACT}" \
  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON \
  -DCMAKE_INSTALL_RPATH:STRING="${ARTIFACT}/lib" \
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -DCMAKE_PREFIX_PATH="${CMAKE_DIR}" \
  .
)
${CMAKE} --build . -- -j ${HASHDIST_CPU_COUNT}
make install
```

while this version of the package:

```
build_stages:

  - name: configure
    build_in_source: false
```

generates:

```
set -e
export HDIST_IN_BUILD=yes
export MACOSX_DEPLOYMENT_TARGET=$(sw_vers -productVersion | sed -E "s/([0-9]+\.[0-9]+).*/\1/")
mkdir -p _build && cd _build
(
export CPPFLAGS="-I${CMAKE_DIR}/include"
export LDFLAGS="-L${CMAKE_DIR}/lib "
${CMAKE} -DCMAKE_INSTALL_PREFIX:PATH="${ARTIFACT}" \
  -DCMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON \
  -DCMAKE_INSTALL_RPATH:STRING="${ARTIFACT}/lib" \
  -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON \
  -DCMAKE_BUILD_TYPE:STRING=Release \
  -DCMAKE_PREFIX_PATH="${CMAKE_DIR}" \
  ..
)
${CMAKE} --build . -- -j ${HASHDIST_CPU_COUNT}
make install
```

### CODE REVIEW

**Comment by chvillanuevap** [comment]
Upon further review, I do not know how this could work with ParMETIS. The issue is that ParMETIS needs two separate build directories: `_build_metis` and `build_parmetis`.

We could create another variable like `build_in_source` called `build_dir`:

```
build_stages:

  - name: configure
    build_in_source: false
    build_dir: _build_metis, _build_parmetis
```

What do you think?

**Comment by certik** [comment]
Parmetic is not build using the cmake template (it calls cmake directly):
```
extends: [base_package]
```
so you do not need to worry about it in this PR.

This PR looks good to me. We can now remove the part
```diff
-  - name: setup_builddir
-    after: prologue
-    handler: bash
-    bash: |
-      mkdir -p _build
-      cd _build
```
from all packages. Before we merge this, I would like to test it on my larger stack, to make sure things still work.

**Comment by chvillanuevap** [comment]
I see what you mean. I saw CMake being used in Parmetis and missed that it depends on the base_package, not the cmake_package. I already modified the other packages. I will commit them at some point tomorrow.

**Comment by chvillanuevap** [comment]
It seems dolfin sets up its CMake file independent of the `cmake_package` configuration file. I duplicated the code from `cmake_package.py` to `dolfin.py`.

**Comment by chvillanuevap** [comment]
I'm going to close this PR, create a branch, and resubmit it. I should not have committed this directly to my master branch.

I want to do this in order to submit a few new packages I have implemented.

**Comment by certik** [comment]
Ok. Please ping me when it is ready. This is a good change.

**Pull request closed without merging**
