### PR TITLE
Update Hashdist to the latest version

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by certik** [comment]
Currently it fails with:
```
$ ./d2/bin/hit
Traceback (most recent call last):
  File "./d2/bin/hit", line 12, in <module>
    from hashdist.cli.main import command_line_entry_point, help_on_exceptions
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/__init__.py", line 1, in <module>
    from .spec.hook_api import *
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/spec/__init__.py", line 1, in <module>
    from .builder import ProfileBuilder
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/spec/builder.py", line 2, in <module>
    from . import package
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/spec/package.py", line 5, in <module>
    from .. import core
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/core/__init__.py", line 4, in <module>
    from .build_store import (ArtifactBuilder, BuildStore, BuildSpec, shorten_artifact_id)
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/core/build_store.py", line 152, in <module>
    from . import run_job
  File "/local/certik/bld/profile/wquc2kwhfrdb/lib/python2.7/site-packages/hashdist/core/run_job.py", line 205, in <module>
    from hashdist.util.logger_setup import suppress_log_info, sublevel_added
ImportError: No module named util.logger_setup
```

**Comment by certik** [comment]
Ok, that failure is fixed by https://github.com/hashdist/hashdist/pull/336, now it fails with:
```
$ ./d2/bin/hit build
No handlers could be found for logger "root"
```

**Comment by certik** [comment]
Ok, that's fixed by https://github.com/hashdist/hashdist/commit/2220b2b3ed0abc3b89ff35dd5b17a2c034f9f8e7, so now https://github.com/hashdist/hashdist/pull/336 fixes all these issues. Once it is merged, I'll updated this PR with the latest git hash.

**Comment by certik** [comment]
As of 611b4f74317dc21d253d27d44b29de97e62d6c46, it now works.

@dagss, @cekees can you please review this?

**Comment by cekees** [comment]
@certik, this is OK with me. I guess we still have to deal with the issue of the bundled depedencies and new  dependencies moving forward.

**Comment by certik** [comment]
Yes, we do. This is just one of the several ways to install Hashdist.

**Pull request merged**
