### PR TITLE
Rethinkdb

### PR DESCRIPTION
**Pull request by vbraun**
This is the database that powers sagemathcoud. It depends on the protobuf update from #878

### CODE REVIEW

**Comment by vbraun** [comment]
There are library linking issues, it picks up unwanted system-wide libraries for me

**Comment by vbraun** [comment]
Now uses hashdist libraries except for the ones dragged in by curl https://github.com/hashdist/hashstack/issues/880

**Comment by cekees** [comment]
+1

**Comment by certik** [comment]
+1

**Pull request merged**
