### PR TITLE
Add jupyter

### PR DESCRIPTION
**Pull request by cekees**
This still needs some cleanup and dependency checking, but I thought I'd go ahead and put it up in case others have suggestions or  concerns.

### CODE REVIEW

**Comment by certik** [comment]
That looks good.

**Comment by minrk** [comment]
Looks sensible, but most of the IPython/Jupyter packages are missing dependencies.

**Comment by ahmadia** [comment]
Have all of these switched to setuptools?  How annoying.

**Comment by cekees** [comment]
That's a fair question. Actually, it looks like the skeleton-pypi command has setuptools hardwired  into the template and that the auto-discovery of dependencies has been left as a todo item.  It may be that most of the packages in this PR could be distutils packages. I don't have time this week, but jupyter might be a good test case for a refactored/extended skeleton-pypi subcommand.

**Comment by minrk** [comment]
@ahmadia none of the IPython or Jupyter packages need setuptools to install. I'm not sure how relevant that is to hashdist, or what hashdist does differently for setuptools vs distutils packages. I would guess that ~all Python packages ought to be installed with `pip install .`, regardless of whether the default behavior is to import setuptools or not.

**Comment by ahmadia** [comment]
We use `python setup.py install` with just `distutils` in the environment for `distutils` packages, and something slightly hairier for `setuptools`.  Generally it's a better idea to avoid adding `setuptools` as an explicit dependency.  Using `pip install .` may be feasible, I've never looked into it.

**Comment by cekees** [comment]
It appears that jupyter needs appnope  and gnureadline on os x as well. 
/cc @guoyinwang

**Comment by certik** [comment]
I fixed it up to work for me and pushed the patches into this PR. I think the dependencies should be more or less correct.

@cekees any objections against merging this? We can always improve on it further once it is in.

**Comment by certik** [comment]
If this works, then let's merge. I am updating to the latest release in #932, but that has its own issues, which are better handled by a separate PR.

**Comment by cekees** [comment]
Sounds good.  I'll wait until the checks complete.

**Comment by certik** [comment]
Checks completed and passed. Merging.

**Pull request merged**
