### PR TITLE
Unset MACOSX_DEPLOYMENT_TARGET for all cmake

### PR DESCRIPTION
**Pull request by certik**
This is needed, otherwise cmake fails to compile packages.

### CODE REVIEW

**Comment by ahmadia** [comment]
This is certainly "new".  This is sometimes needed to make Python packages build correctly, and for enforcing deployment targets.

**Comment by certik** [comment]
There might be some way to convince CMake to work with MACOSX_DEPLOYMENT_TARGET. I found, as you said, that Python (and perhaps more packages) require MACOSX_DEPLOYMENT_TARGET to be properly set so I set it in PROLOGUE. However, cmake always fails to build other packages, if this is set --- so one solution is to unset MACOSX_DEPLOYMENT_TARGET just for packages build using cmake, the other solution is to figure out how to make cmake work with it (I think that would be preferable, probably). This PR implements the former.

**Comment by johannesring** [comment]
See also issue #368.

**Comment by certik** [comment]
See also #/902. It looks like on El Capitan at least, things are working as expected.

**Pull request closed without merging**
