### PR TITLE
Bump SWIG version to 3.0.5

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by certik** [comment]
Can you remind me which packages needed the old version of SWIG? I assume they don't need it anymore?

**Comment by johannesring** [comment]
@certik - Trilinos 11.10.2 did not work with SWIG later than 2.0.8.

**Comment by johannesring** [comment]
Any objections for merging this?

**Comment by certik** [comment]
It's fine with me.

**Comment by johannesring** [comment]
Thanks.

**Pull request merged**
