### PR TITLE
added  pcs_api and dependencies

### PR DESCRIPTION
**Pull request by cekees**
dependencies for https://github.com/hashdist/hashdist/pull/314

### CODE REVIEW

**Comment by certik** [comment]
That looks good. You can safely delete the empty `[]` lines.

**Comment by johannesring** [comment]
Is there some missing dependencies for `requests_oauthlib`? In `setup.py` I see this:

    install_requires=['oauthlib>=0.6.2', 'requests>=2.0.0'],

**Comment by certik** [comment]
@johannesring which `setup.py` do you see this in?

**Comment by cekees** [comment]
https://github.com/requests/requests-oauthlib/blob/master/setup.py. @johannesring is  correct.  I will fix this by hand, but I put a hashdist issue here: https://github.com/hashdist/hashdist/issues/338

**Comment by certik** [comment]
Looks good to me.

**Pull request merged**
