### PR TITLE
Bump fenics packages to version 1.6.0

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by certik** [comment]
So actually it looks like this PR fails:
```
Downloading https://bitbucket.org/fenics-project/ffc/downloads/ffc-1.6.0.tar.gz...

[INFO] Downloading 'https://bitbucket.org/fenics-project/ffc/downloads/ffc-1.6.0.tar.gz'

[=========================] 100.0% (0.4MB of 0.4MB) 20.010MB/s ETA 0s  

[ffc] Building ffc/6k7lndnxzlej, follow log with:

[ffc]   tail -f /home/travis/.hashdist/tmp/ffc-6k7lndnxzlej/_hashdist/build.log

[ffc] running [u'/bin/bash', '_hashdist/build.sh']

[ffc] environment:

[ffc]   {'ARTIFACT': u'/home/travis/.hashdist/bld/ffc/6k7lndnxzlej',

[ffc]    'BASH': u'/bin/bash',

[ffc]    'BUILD': u'/home/travis/.hashdist/tmp/ffc-6k7lndnxzlej',

[ffc]    'HASHDIST_CPU_COUNT': '1',

[ffc]    'HDIST_CONFIG': '{"gc_roots":"/home/travis/.hashdist/gcroots","build_stores":[{"dir":"/home/travis/.hashdist/bld"}],"source_caches":[{"dir":"/home/travis/.hashdist/src"}],"cache":"/home/travis/.hashdist/cache","build_temp":"/home/travis/.hashdist/tmp"}',

[ffc]    'HDIST_IMPORT': u'numpy/cv23k4vxglxqantuwn5uf7j4rtxsqvl5 patchelf/k3rloj265ogtl4dmmmbmyt34dnffryka python/vocgqpztn6ne3pwxfogalqgbimemjhch swig/uekwyqtbddiqgzlwr7szmu4l5tbi6zjp',

[ffc]    'HDIST_IMPORT_PATHS': u'/home/travis/.hashdist/bld/numpy/cv23k4vxglxq:/home/travis/.hashdist/bld/patchelf/k3rloj265ogt:/home/travis/.hashdist/bld/python/vocgqpztn6ne:/home/travis/.hashdist/bld/swig/uekwyqtbddiq',

[ffc]    'HDIST_VIRTUALS': '',

[ffc]    u'NUMPY_DIR': u'/home/travis/.hashdist/bld/numpy/cv23k4vxglxq',

[ffc]    u'NUMPY_ID': u'numpy/cv23k4vxglxqantuwn5uf7j4rtxsqvl5',

[ffc]    'PATCHELF': u'/home/travis/.hashdist/bld/patchelf/k3rloj265ogt/bin/patchelf',

[ffc]    u'PATCHELF_DIR': u'/home/travis/.hashdist/bld/patchelf/k3rloj265ogt',

[ffc]    u'PATCHELF_ID': u'patchelf/k3rloj265ogtl4dmmmbmyt34dnffryka',

[ffc]    'PATH': u'/usr/bin:/bin',

[ffc]    'PWD': u'/home/travis/.hashdist/tmp/ffc-6k7lndnxzlej',

[ffc]    'PYTHON': u'/home/travis/.hashdist/bld/python/vocgqpztn6ne/bin/python',

[ffc]    'PYTHONPATH': u'/home/travis/.hashdist/bld/numpy/cv23k4vxglxq/lib/python2.7/site-packages',

[ffc]    u'PYTHON_DIR': u'/home/travis/.hashdist/bld/python/vocgqpztn6ne',

[ffc]    u'PYTHON_ID': u'python/vocgqpztn6ne3pwxfogalqgbimemjhch',

[ffc]    u'SWIG_DIR': u'/home/travis/.hashdist/bld/swig/uekwyqtbddiq',

[ffc]    'SWIG_EXECUTABLE': u'/usr/bin/swig',

[ffc]    u'SWIG_ID': u'swig/uekwyqtbddiqgzlwr7szmu4l5tbi6zjp'}

[ffc] Traceback (most recent call last):

[ffc]   File "setup.py", line 305, in <module>

[ffc]     run_install()

[ffc]   File "setup.py", line 208, in run_install

[ffc]     SWIG_EXECUTABLE = get_swig_executable()

[ffc]   File "setup.py", line 73, in get_swig_executable

[ffc]     raise OSError("Unable to find SWIG version %s or higher." % swig_minimum_version)

[ffc] OSError: Unable to find SWIG version 3.0.3 or higher.

[ffc|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1

[ffc|ERROR] command failed (code=1); raising

```
So this needs to be fixed.

**Comment by johannesring** [comment]
Thanks. FFC and DOLFIN now requires SWIG >= 3.0.3, so the fix is to either bump the default version in hashstack or to update `test.dolfin.yaml`. Any preference? I prefer bumping the default version, but I'm fine either way.

**Comment by certik** [comment]
Just bump the default version.

**Comment by johannesring** [comment]
Sorry, it turns out that we already have SWIG 3.0.5 as the default version in HashStack. The problem is that `test.dolfin.yaml` uses `host-swig`, the version in Ubuntu, which is an old version of SWIG. Since the test is already close to the 50 min timeout, I will enable building of SWIG with HashDist but will use `host-boost` to save some time.

**Comment by certik** [comment]
I am fine with the idea behind the change.

The test fails, dolphin can't find VTK.

**Comment by johannesring** [comment]
The error is not because DOLFIN can't find VTK. I think the problem is hidden because we only show the 60 last lines of `log.txt`. How about increasing the number of lines to, say 100?

**Comment by johannesring** [comment]
I increased the number of lines to 100 and it turns out that the problem is that the default Boost version was too old (DOLFIN needs at least version 1.48). I have just pushed a fix for this in `travis.yml`.

**Comment by johannesring** [comment]
The test passed so I merged this.

**Pull request merged**
