### PR TITLE
add proteus.tamucluster.yaml to stack/examples 

### PR DESCRIPTION
**Pull request by srobertp**
which gives a stack profile for users who wish to build on the numerical analysis Mathematics clusters located at texas a&m university.

### CODE REVIEW

**Comment by certik** [comment]
+1

**Comment by cekees** [comment]
+1 

Just for future reference, it might be worth switching to the hashstack version of cmake eventually instead of relying on the /w/srobertp version of cmake via host-cmake.

**Comment by srobertp** [comment]
@cekees good idea. That would make this .yaml file general for those who want to use it on the tamu cluster.

**Comment by cekees** [comment]
This a proteus HPC  profile, so the test failures are unrelated.

**Pull request merged**
