### PR TITLE
superlu_dist: remove -j option

### PR DESCRIPTION
**Pull request by johannesring**

### CODE REVIEW

**Comment by johannesring** [comment]
This will probably fix #715.

**Comment by certik** [comment]
+1, but can you verify that it fixes #715?

**Comment by johannesring** [comment]
@certik - No, it didn't fix #715. However, removing the `-j` option when building the library did fix the problem.

**Comment by certik** [comment]
Ok, +1 to merge now.

**Comment by johannesring** [comment]
Thanks @certik.

**Comment by vincentkersten** [comment]
Thanks guys - I - or better the server - finished compiling on PROC=1 this morning and all works, very tempted to build again with PROCS=48 :)
Keep up the good workz

**Pull request merged**
