### PR TITLE
Add Ninja

### PR DESCRIPTION
**Pull request by certik**
This can be used with `cmake`, just pass `-G Ninja` to it. Works great.

### CODE REVIEW

**Comment by ahmadia** [comment]
Any particular reason you didn't point to a release?

**Comment by certik** [comment]
I did.

**Comment by ahmadia** [comment]
Ahh, the Git repository is the slowest way to get sources, since the entire Git repository is cloned.  You're better off pointing to a tarball like this one: https://github.com/martine/ninja/archive/v1.5.3.tar.gz

**Comment by certik** [comment]
I see. Fixed.

**Comment by ahmadia** [comment]
+ 1

**Comment by ahmadia** [comment]
err, +1

**Comment by certik** [comment]
Thanks for the review. You know that you can modify comments. ;)

**Comment by robertmaynard** [comment]
Have you looked at using ```--depth 1``` with git to make checkouts faster as that does a shallow clone ( no history )?

Just an FYI: Certain things that are possible with makefiles are impossible with ninja currently, so switching from make to ninja as the CMake generator could cause builds to fail. It is fairly rare, but is usually caused by incomplete listing of outputs from ```add_custom_commands```, ```add_custom_commands``` with the ```POST_BUILD ```  options, or incomplete consumption of outputs from ```custom_commands```

**Comment by certik** [comment]
Also ninja doesn't work for Fortran, so I can't use it myself or my work anyway.

@robertmaynard, I got the idea from @thewtex who suggested [here](https://plus.google.com/u/0/111200425937199925962/posts/1DywGBxDXTt) that "the Ninja generator is highly recommended!﻿", but the Fortran support needs to be added first.

**Comment by ahmadia** [comment]
> Have you looked at using --depth 1 with git to make checkouts faster as that does a shallow clone ( no history )?

This was one of the very first suggestions I made to Dag when I joined the team.  Because we are grabbing commits and not refs, we can't actually use `--depth 1`, since there is no way to request a remote commit from a repository, only a ref.

**Comment by robertmaynard** [comment]
@certik For well behaved CMake projects that only use C/C++ ninja is a good choice.  Brad King has proposed adding Fortran support to ninja, but that is still in progress.

**Pull request merged**
