### PR TITLE
updated petsc4py and  daetk to work with petsc v3.6.1

### PR DESCRIPTION
**Pull request by cekees**
@johannesring I tested the petsc 3.6.1 version you added, and it is working fine for me. This PR has some of the changes petsc4py and daetk that  I ended up making to run proteus with the new version.

### CODE REVIEW

**Comment by certik** [comment]
+1 from me.

**Comment by johannesring** [comment]
Is the patch for petsc4py something that should be applied upstream?

Otherwise +1 from me.

**Comment by cekees** [comment]
Good idea.  I'll discuss  it  upstream.

**Comment by ahmadia** [comment]
@cekees : see https://bitbucket.org/petsc/petsc4py/issues/2/consider-adding-conf-to-petsc4py-install

**Comment by cekees** [comment]
OK, thanks. I see his  point. I can take a look at getting the info I need from somewhere else.

**Pull request merged**
