### PR TITLE
boost: add patch to fix problems with gcc5

### PR DESCRIPTION
**Pull request by johannesring**
This fixes issue #802.

### CODE REVIEW

**Comment by certik** [comment]
That's fine. But we can also just update Boost, isn't it easier?

**Comment by johannesring** [comment]
Updating Boost is the better solution, but this requires more testing and we also have some other patches that needs attention if we update, so for now it was easier for me to just add the patch.

**Comment by certik** [comment]
@johannesring  +1 to this PR then.

Not related to this PR, except using gcc 5, but I was wondering if you knew how to fix #747. It'd be nice to have gcc 5 in Hashstack itself.

**Comment by johannesring** [comment]
Thanks @certik.

I'm not sure about #747, but I can take a look after the FEniCS workshop next week.

**Pull request merged**
