### PR TITLE
added  pythreejs pkg

### PR DESCRIPTION
**Pull request by cekees**
requires #839

### CODE REVIEW

**Comment by jcftang** [comment]
+1

**Comment by certik** [comment]
I fixed the style. +1 now.

**Comment by cekees** [comment]
@certik it looks like the checks fails just because of random slow tests taking over 50min. Have you just been merging PR's in this case? I don't see any way that this pkg could cause a test failure.

**Comment by johannesring** [comment]
The dolfin test is failing for some reason and it is not because of a timeout. I tried to force a rebuild but it failed at the same place and I don't see why because we only see the last 60 lines of `log.txt`. I don't see why adding this package should cause any problems, so I am fine with merging this.

**Comment by certik** [comment]
Yes, I was merging it if it goes over 50min.

**Pull request merged**
