### PR TITLE
Update cmake to 3.4.2

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by johannesring** [comment]
I have tested this with my FEniCS profiles and it fails for mshr. Maybe we should have a `version` parameter for CMake like we have for PETSc?

**Comment by jcftang** [comment]
@johannesring what's the error?

**Comment by johannesring** [comment]
@jcftang - The error happens when mshr tries to build CGAL (mshr includes its own copy of CGAL). I don't remember exactly what the error was, but it is not important since the problem has been fixed in the development version of mshr by updating CGAL. I'm okay with merging this, but it will require an update of the mshr package. That should be fine since the development version of mshr should work with the stable version of the other FEniCS packages.

**Comment by certik** [comment]
If it was fixed in some of those packages, then I think we should just merge this and then update those. I am merging this. @johannesring let me know if you need help with the `mshr` package.

**Pull request merged**
