### PR TITLE
Update PETSc and friends to 3.6

### PR DESCRIPTION
**Pull request by johannesring**
This PR adds sources for version 3.6 of PETSc and friends (petsc4py, SLEPc and slepc4py). The default version is still 3.5 but I would like to update the default to 3.6 if there are no objections.

### CODE REVIEW

**Comment by johannesring** [comment]
Any comments on this?

**Comment by ahmadia** [comment]
+1

**Comment by ahmadia** [comment]
I haven't run this but this looks good.

**Comment by johannesring** [comment]
It works for us on both [Linux](https://bitbucket.org/fenics-project/fenics-developer-tools/raw/b300fdb56981bac9a34b43dd3898b07869267c3e/install/profiles/fenics.Linux.yaml) and [OS X](https://bitbucket.org/fenics-project/fenics-developer-tools/raw/b300fdb56981bac9a34b43dd3898b07869267c3e/install/profiles/fenics.Darwin.yaml), but I haven't tested on Cygwin yet.

**Comment by ahmadia** [comment]
I'd suggest merging.  Cygwin is a bit of a second-class citizen :)

**Comment by johannesring** [comment]
@ahmadia - any comments on whether to keep 3.5.2 as the default version or to switch to 3.6.1 as default?

**Comment by ahmadia** [comment]
I'd check with @certik and @cekees before changing the default PETSc version.

**Comment by johannesring** [comment]
Yes, I will wait for them to comment. Thanks!

**Comment by cekees** [comment]
+1 on this as well.  Thanks for pinging me. We're not quite ready to test it with the proteus stack, but we're insulated from changes to master so it won't hurt us to merge now. It may be several  weeks before we test the new versions of  petsc and superlu_dist.

**Comment by johannesring** [comment]
Ok, let's keep 3.5.2 as the default for now.

**Comment by certik** [comment]
+1

**Pull request merged**
