### PR TITLE
Upgrade statsmodels to 0.6.1

### PR DESCRIPTION
**Pull request by certik**

### CODE REVIEW

**Comment by jcftang** [comment]
Should this PR be rebased?

**Comment by certik** [comment]
I just did. I didn't know what happened here before.

**Comment by certik** [comment]
I also pushed in a fix for `cvxopt`, now `statsmodels` build just fine on my computer.

**Comment by certik** [comment]
@cekees, would you mind reviewing it please?

**Comment by certik** [comment]
It works for me, there are no objections, I am going to merge this, as I hit this error again today.

**Pull request merged**
