### PR TITLE
python-from-host: use HOST_PYTHON to get Python install dir

### LINKED ISSUE #882: Python from host fails when not installed under /usr
``` console
[python] Building python/qlvjlzdbishm, follow log with:
[python]   tail -f /cluster/home/johannr/.hashdist/tmp/python-qlvjlzdbishm-1/_hashdist/build.log
[python] running [u'/bin/bash', '_hashdist/build.sh']
[python] environment:
[python]   {'ARTIFACT': u'/cluster/home/johannr/.hashdist/bld/python/qlvjlzdbishm',
[python]    'BASH': u'/bin/bash',
[python]    'BUILD': u'/cluster/home/johannr/.hashdist/tmp/python-qlvjlzdbishm-1',
[python]    'HASHDIST_CPU_COUNT': '1',
[python]    'HDIST_CONFIG': '{"gc_roots":"/cluster/home/johannr/.hashdist/gcroots","build_stores":[{"dir":"/cluster/home/johannr/.hashdist/bld"}],"source_caches":[{"dir":"/cluster/home/johannr/.hashdist/src"}],"cache":"/cluster/home/johannr/.hashdist/cache","build_temp":"/cluster/home/johannr/.hashdist/tmp"}',
[python]    'HDIST_IMPORT': '',
[python]    'HDIST_IMPORT_PATHS': '',
[python]    'HDIST_VIRTUALS': '',
[python]    'PATH': u'/usr/bin:/bin',
[python]    'PWD': u'/cluster/home/johannr/.hashdist/tmp/python-qlvjlzdbishm-1'}
[python] cp: cannot stat `/usr/bin/python2.7': No such file or directory
[python|ERROR] Command '[u'/bin/bash', '_hashdist/build.sh']' returned non-zero exit status 1
[python|ERROR] command failed (code=1); raising
```
I will prepare a pull request.

### PR DESCRIPTION
**Pull request by johannesring**
This will fix #882.

### CODE REVIEW

**Comment by johannesring** [comment]
The test `test.host-scipy.yaml` is failing because `HOST_PYTHON` is not set in `suse.yaml`. We can either fix this by setting `HOST_PYTHON` in `suse.yaml` or extending from `debian.yaml` instead of `suse.yaml` in `test.host-scipy.yaml`. Maybe we should do both?

**Comment by cekees** [comment]
My vote  would be just to put  it  in suse.yaml and not extend  from debian.yaml. I could be  wrong, but I  thought the idea was to loosely mirror the ancestry of the linux distributions with these  basic  profiles  like suse.yaml and debian.yaml, and I don't  think suse descends from debian.

**Comment by johannesring** [comment]
Thanks for your comment. I have added `HOST_PYTHON` now in `suse.yaml`.

**Comment by johannesring** [comment]
Should we add `HOST_PYTHON` in the other basic profiles like `centos.yaml`, `darwin.yaml`, `homebrew.yaml`, `linux.yaml`, `osx_clt.yaml` and `osx.yaml`? It has already been set in `arch.yaml`, `cygwin.yaml`, `debian.yaml` and `macports.yaml`.

**Pull request merged**
