### PR TITLE
[WIP] Python on Cygwin64.

### PR DESCRIPTION
**Pull request by memmett**
This is close to working: some extension modules aren't being detected/compiled properly.  I think this may have something to do with how broken Windows is with respect to locating dynamic libraries (ie, no RPATH, just PATH).

Will do some more investigating now that I know about `cygcheck`.

### CODE REVIEW

**Comment by certik** [comment]
+1. Did you figure out all these patches by yourself? Impressive work.

**Comment by jcftang** [comment]
+1

**Comment by memmett** [comment]
@certik Nope, I pulled in the patches from the cygwinports/python project...

**Comment by cekees** [comment]
I'll try to test this out on a windows image at some point soon, but @memmett if you've got a stack that is working for you, then I'd vote for merging in all the cygwin support as soon as you're happy with it. Unless others are using the cygwin support and want to be more conservative. We don't have anybody currently using the proteus cygwin stack.

**Comment by certik** [comment]
+1 to merge from me

**Comment by memmett** [comment]
@cekees Alrighty, will do (sometime in the next few days).

**Comment by memmett** [comment]
I built this again today and I'm happy with it.  The users Cygwin install should include: libcrypt-devel, libexpat-devel, libffi-devel.  All other dependencies are built by hashdist.

**Pull request merged**
