### PR TITLE
gcc: install fixed dispatch/object.h header file

### LINKED ISSUE #742: OS X 10.10: /usr/include/dispatch/object.h doesn't work with gcc
This is hit by many packages, and manifests as follows:
```
[gettext-bootstrap] libtool: compile:  gcc -c -DLOCALEDIR=\"/Users/certik/.hashdist/bld/gettext-bootstrap/spt6nwddjz7d/share/locale\" -DLOCALE_ALIAS_PATH=\"/Users/certik/.hashdist/bld/gettext-bootstrap/spt6nwddjz7d/share/locale\" -DLIBDIR=\"/Users/certik/.hashdist/bld/gettext-bootstrap/spt6nwddjz7d/lib\" -DBUILDING_LIBINTL -DBUILDING_DLL -DIN_LIBINTL -DENABLE_RELOCATABLE=1 -DIN_LIBRARY -DINSTALLDIR=\"/Users/certik/.hashdist/bld/gettext-bootstrap/spt6nwddjz7d/lib\" -DNO_XMALLOC -Dset_relocation_prefix=libintl_set_relocation_prefix -Drelocate=libintl_relocate -DDEPENDS_ON_LIBICONV=1 -DHAVE_CONFIG_H -I. -I. -I.. -I/Users/certik/.hashdist/bld/libiconv-bootstrap/y6dz7hsnygn3/include -g -O2 -fvisibility=hidden ./log.c  -fno-common -DPIC -o .libs/log.o
[gettext-bootstrap] In file included from /usr/include/dispatch/dispatch.h:51:0,
[gettext-bootstrap]                  from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
[gettext-bootstrap]                  from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
[gettext-bootstrap]                  from ./langprefs.c:29:
[gettext-bootstrap] /usr/include/dispatch/object.h:143:15: error: expected identifier or '(' before '^' token
[gettext-bootstrap]  typedef void (^dispatch_block_t)(void);
[gettext-bootstrap]                ^
[gettext-bootstrap] /usr/include/dispatch/object.h:362:3: error: unknown type name 'dispatch_block_t'
[gettext-bootstrap]    dispatch_block_t notification_block);
[gettext-bootstrap]    ^
```
E.g. https://github.com/hashdist/hashdist/issues/332 is a duplicate of this bug.

To fix this, we need to ship the fixed header file with our gcc.

### PR DESCRIPTION
**Pull request by certik**
Fixes #742.

I tested this, it is ready for review.

### CODE REVIEW

**Comment by certik** [comment]
I see, I should check first that the file exists, perhaps only do this on OS X 10.10 (previous versions do not have this problem).

**Comment by certik** [comment]
Done, it now tests if the file exists. I think that is sufficient, if the file exists but doesn't have the bug, it will just copy it, which should be safe.

**Comment by certik** [comment]
It still works on my OS X.

**Comment by jcftang** [comment]
+1 looks good to me

**Comment by certik** [comment]
Thanks for the review, this PR is essential for OS X.

**Pull request merged**
