### PR TITLE
Update paraview to 4.3.1

### PR DESCRIPTION
**Pull request by certik**
I built it and tested it, it seems to be working.

### CODE REVIEW

**Comment by certik** [comment]
@robertmaynard --- I found a curious thing --- the GMV reader plugin is available in ParaView 4.0.1 in Ubuntu as well as in the version 4.3.1 that this PR introduces. However, for some reason the plugin is not available in ParaView 4.1.0 (currently in Hashstack). Here is the build log of the current Hashstack's paraview on my laptop: https://gist.githubusercontent.com/certik/caed725cc9d2c8e45c69/raw/build.log, it looks like the GMV plugin is being built (`2015/02/27 18:21:44 - INFO: [package:run_job] -- Plugin: GMVReader - Reader for binary or ASCII files stored in General Mesh Viewer file format : Enabled`), but then it is not listed in the list of plugins --- however, ParaView can still load GMV files, except that it can't handle time series (i.e. I have files of the type `data.gmv.00??`).

The Ubuntu version as well as this PR's version seem to work fine for me.

**Comment by robertmaynard** [comment]
ParaView has two GMV Readers, once comes from the VisItBridge and the other from a Plugin. I expect that this is causing the problem with ParaView 4.1.0

**Comment by certik** [comment]
Hm, so on my work machine, both ParaView 4.1.0 and 4.3.1 behave exactly the same: both load GMV as a plugin. On my laptop, I only compiled ParaView 4.1.0 so far, and the plugin is missing there.

**Comment by certik** [comment]
@ahmadia any objections against merging this?

**Comment by ahmadia** [comment]
Go ahead.

**Comment by certik** [comment]
Thanks!

**Pull request merged**
